#
# Include a space ONLY at the front of a string that requires it.
#

camping_sentence_chunks = ["Dear diary,\nThis weekend I am going camping with", ". I packed my lantern, sleeping bag, and", ". I am so", " to", " in a tent. I am", " we might see a", ", they are kind of dangerous. We are going to hike, fish, and", ". I have heard that the", " lake is great for", ". Then we will", " hike through the forest for", "", ". If I see a", "", " while hiking, I am going to bring it home as a pet! At night we will tell", "", " stories and roast", " around the campfire!"]

hospital_sentence_chunks = ["It was about", "", " ago when I came to the hospital in a", ". The hospital is a/an", " place, there are a lot of", "", " here. There are nurses here who have", "", ". If someone wants to come into my room I told them that they have to", " first. I have decorated my room with", "", ". Today a doctor came into my room and they were wearing a", " on their", ". I heard that all doctors", "", " every day for breakfast. The most ", " thing about being in the hospital is the", "", "!"]

zoo_sentence_chunks = ["Dear diary,\nToday I went to the zoo. I saw a(n)", "", " jumping up and down in its tree. He", "", " through the large tunnel that led to its", "", ". I got some peanuts and passed them through the cage to a gigantic", "", " towering above my head. Feeding that animal made me", ". I went to get a", " scoop of ice cream. It filled my stomach. Afterwards I had to", "", " to catch our bus. When I got home I", " my mom for a", " day at the zoo!"]

enchanted_forest_chunks = ["Dear", ",\nI am writing to you from a", " castle in an enchanted forest. I found myself here one day after going for a ride on a", "", " in", ". There are", "", " and", "", " here! In the", " there is a pool full of", ". I fall asleep each night on a", " of", " and dream of", "", ". It feels as though I have lived here for", "", ". I hope one day you can visit, although the only way to get here now is", " on a", "", "!!"]

pizza_chunks = ["Pizza! Pizza! Pizza!\nPizza was invented by a", "", " chef named", ". To make a pizza, you need to take a lump of", ", and make a thin, round", "", ". Then you cover it with", " sauce,", " cheese, and fresh chopped", ". Next you have to bake it in a very hot", ". When it is done, cut it into", "", ". Some kids like", " pizza the best, but my favorite is the", " pizza. If I could, I would eat pizza", " times a day!"]

animals_chunks = ["Once upon a time,\nThere was a", "", " from", ". Nobody knew he was a", " because he had", " fur and ate", "", " each day. He liked to", " and sing", ". Whenever he was", ", he would start speaking", ". Then he would feel", "."]

recipe_chunks = ["Let's make", "!\nTo make", " you first need to gether your ingredients. You'll need", " eggs, a", " of milk, flour, sugar, and", " butter. Start by", "", " together the", " ingredients in a bowl. Then,", " in the milk, eggs, and", " butter. Once the", " is", ", you're ready to", "! Scoop the batter onto a/an", "", " and cook until all the bubbles", ". The", " part about making", " is piling them onto your", ", loading them with your", " toppings, and digging in!"]

mad_scientist_chunks = ["Dear diary,\nToday we had a substitute teacher for science class, with", " hair that", " straight up", " inches high. His name was Mr.", " and he said he'd show us why science was the most", " class. First, he used a", " and a", " to make a", " of water turn", ". Then he made a", " of the solar system using", ",", ", and", ". When the principal walked by and saw the substitute teacher using", " to", "", " the", " into", "", ", she asked him to show the class a movie about", " instead. The next day, we had a different substitute teacher."]